language: node_js
sudo: required
addons:
  apt:
    packages:
    - lftp
node_js:
- 0.12.3
before_script:
- npm install -g harp
- chmod +x ./deployMaster.sh
script:
- if [ $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "master" ] ; then ./deployMaster.sh;
  fi
env:
  global:
    secure: J8L3g605yfSVZe+IwF0Kgi1VDXvo+J/nQWRi44pkyy1NXrDwTZpRqpzB7WxYYKff1XSgvdUja6tXy/WvxUmthtLyOSG5p0ToKJFWzFLNZU0WxXcJbXWW2CrWkO3grcSo1d7bx1lmGKDDSbsErzHL1EvNMwv1/uMVOipVwRZMx3Z5IG9C/PRaDhHd3q9FgEQDy8J2mddAs8CJfYN0Y18HAzPqk6eUhSmHZXD/CfFl7e7q3NHzuELuXkIKzZwSlcFzPlXpHWR0bM5tgJtXvsDIpCrTFXKKdJ80VdN8bQu7KUzwCcbTTmMKvVjCfDhact2Q2FyTUu7BNQJ0P+lxvobR318+YQ1hltU6jDe5/2SwMPd+Ej8FhIboWm61HEunPd/UdaYz1b4KAX1O8u+gQKdG5OGRcCbCWAvD/P2VF7Ve/eP7OG/dlPn5SOyg/P9LoinuxeiZs7hwEymFjJl2owsdLZY8FRh8F7B09rDVYzR0adq2JPP/c4dy6eqQrG0MeYbKK4npO9tz5d4nwXuXct5ip9qkNeCh5WNxEs1fZa+iFDi+WqdWE1LKWAggYNQt50vXrL+c0jbGR8G3R8sjsDJ3hN9lMvwBTMMh18nsEQy7vRDyjKKXvc7f4eqBgdnH1kdJObRbwDPkjJwb891d1QFHc48RsapQuujwxydFUrfXTSE=
