#!/bin/bash

echo "Starting deployment"
TEMP_DIRECTORY="/tmp/__temp_static_content"
CURRENT_COMMIT=`git rev-parse HEAD`
ORIGIN_URL="github.com/gobstones/gobstones.github.io.git"
ORIGIN_URL_WITH_CREDENTIALS="https://${GITHUB_TOKEN}@${ORIGIN_URL}"

echo "Compiling site into " ${TEMP_DIRECTORY}
mkdir ${TEMP_DIRECTORY}
harp compile -o ${TEMP_DIRECTORY} || exit 1

echo "Tuning .gitinore files to select which files to push into gobstones.github.io master"
cp .gitignore ${TEMP_DIRECTORY}

# Ignore .gitignore itself
echo .gitignore >> ${TEMP_DIRECTORY}/.gitignore

# Do not ignore generated files in /assets
rm ${TEMP_DIRECTORY}/assets/.gitignore

echo "Pushing into " ${ORIGIN_URL}
cd ${TEMP_DIRECTORY}
echo "## Autogenerated site for [Gobstones](http://gobstones.github.io)" > Readme.md

git init
git config user.name "Travis-CI" || exit 1
git config user.email "travis@gobstones.com" || exit 1
git add --all
git commit --allow-empty -m "Generated static site for $CURRENT_COMMIT" || exit 1
git remote add origin "$ORIGIN_URL_WITH_CREDENTIALS"
git push -u --force --quiet origin master > /dev/null 2>&1

echo "Cleaning up temp files"
rm -Rf ${TEMP_DIRECTORY}

echo "Deployed successfully."
exit 0